"""Add activation_date and last_renewal_date to Organization model

Revision ID: 4a19cc9f79a6
Revises: 
Create Date: 2025-08-03 20:21:41.468319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a19cc9f79a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activation_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_renewal_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('last_renewal_date')
        batch_op.drop_column('activation_date')

    # ### end Alembic commands ###
